apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    url: http://influxdb:8086
    database: monitoring
    isDefault: true
    editable: true
    jsonData:
      httpMode: GET
      queryType: influxql
